# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
- repo: self

variables:
- name: env
  value: stage

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: echo '##vso[task.setvariable variable=env]prod'
      condition: eq(variables['Build.SourceBranchName'], 'master')
    - task: Npm@1
      displayName: Install npm packages
      inputs:
        command: 'install'
    - task: Npm@1
      displayName: Build next.js project
      inputs:
        command: 'custom'
        customCommand: 'run build'
    - task: Docker@2
      condition: ne(variables['Build.Reason'], 'PullRequest') #Skip step image build if Pull Request
      displayName: Build an image
      inputs:
        containerRegistry: 'artportable-image-repository'
        repository: 'artportable-web'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          $(Build.BuildId)-$(Build.SourceBranchName)
        arguments: '--build-arg ENV=$(env)'
    - task: Docker@2
      condition: ne(variables['Build.Reason'], 'PullRequest') #Skip step image build if Pull Request
      displayName: Push image
      inputs:
        containerRegistry: 'artportable-image-repository'
        repository: 'artportable-web'
        command: 'push'
        tags: |
          $(Build.BuildId)
          $(Build.BuildId)-$(Build.SourceBranchName)
