import { makeStyles, Theme, createStyles } from "@material-ui/core/styles";

export const styles = makeStyles((theme: Theme) =>
  createStyles({
    paymentOptions: {
      gridArea: "paymentOptions",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
    },
    planCards: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      [theme.breakpoints.up("md")]: {
        flexDirection: "row",
        width: "auto",
      },
    },
    joinCommunityButton: {
      margin: theme.spacing(4),
      display: "flex",
      justifyContent: "center",
      "& button": {
        flexGrow: 1,
        maxWidth: "280px",
      },
    },
    plansContainer: {
      display: "block",
      backgroundColor: "transparent",
      [theme.breakpoints.up("smPlus")]: {
        marginBottom: "auto",
      },
    },
    plansIntervalContainer: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      margin: "0 auto",
      backgroundColor: "transparent",
      "& .MuiToggleButtonGroup-groupedHorizontal": {
        border: "none",
        color: "#000000",
      },
      "& .MuiToggleButton-root.Mui-selected": {
        color: "#000000",
        backgroundColor: "transparent",
        borderBottom: "2px solid #000000",
        borderRadius: "0",
      },
      [theme.breakpoints.up("smPlus")]: {
        paddingTop: "20px",
      },
    },
    planToggleButton: {
      textTransform: "none",
      fontSize: "1.3rem",
      marginLeft: "40px",
      marginRight: "40px",
      fontWeight: 400,
    },
    planCardsContainer: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      [theme.breakpoints.up("smPlus")]: {
        flexDirection: "row",
        justifyContent: "space-evenly",
      },
    },
    desktopTableContainer: {
      width: "100%",
      maxWidth: "1000px",
      margin: "0 auto",
      padding: "40px 20px",
      fontFamily: "Roboto",
      backgroundColor: "transparent",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
    },
    tableTitle: {
      fontSize: "32px",
      fontWeight: 500,
      color: "#333",
      textAlign: "left",
    },
    planHeadersRow: {
      display: "grid",
      gridTemplateColumns: "1fr 200px 200px 200px",
      gap: "12px",
      marginBottom: "20px",
      alignItems: "flex-end",
      justifyContent: "center",
      width: "100%",
      maxWidth: "1000px",
    },
    emptyHeaderCell: {
      // Empty space for the feature column
    },
    planHeaderBoxGray: {
      backgroundColor: "#DBDBDB",
      borderRadius: "10px",
      padding: "16px 12px",
      textAlign: "center",
      fontSize: "18px",
      fontWeight: 500,
      color: "#333",
      minHeight: "60px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      width: "100%",
      boxSizing: "border-box",
    },
    planHeaderBoxWhite: {
      backgroundColor: "#DBDBDB",
      borderRadius: "10px",
      padding: "16px 12px",
      textAlign: "center",
      fontSize: "18px",
      fontWeight: 500,
      color: "#333",
      minHeight: "60px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      width: "100%",
      boxSizing: "border-box",
    },
    planHeaderBoxSelected: {
      backgroundColor: "#A70201",
      borderRadius: "10px",
      padding: "16px 12px",
      textAlign: "center",
      fontSize: "18px",
      fontWeight: 500,
      color: "#ffffff",
      cursor: "pointer",
      minHeight: "60px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      width: "100%",
      boxSizing: "border-box",
    },

    planHeaderBoxCurrent: {
      backgroundColor: "#4CAF50",
      borderRadius: "10px",
      padding: "16px 12px",
      textAlign: "center",
      fontSize: "18px",
      fontWeight: 500,
      color: "#ffffff",
      cursor: "pointer",
      border: "2px solid #2E7D32",
      position: "relative",
      minHeight: "60px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      width: "100%",
      boxSizing: "border-box",
    },

    planHeaderContainer: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      position: "relative",
      width: "100%",
      minHeight: "90px",
      justifyContent: "flex-end",
    },

    currentPlanLabel: {
      fontSize: "12px",
      fontWeight: 600,
      color: "#4CAF50",
      textTransform: "uppercase",
      marginBottom: "8px",
      letterSpacing: "0.5px",
    },

    currentPlanBadge: {
      position: "absolute",
      top: "-8px",
      right: "-8px",
      backgroundColor: "#4CAF50",
      color: "white",
      borderRadius: "50%",
      width: "24px",
      height: "24px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "14px",
      fontWeight: "bold",
      border: "2px solid #ffffff",
    },
    tableRow: {
      display: "grid",
      gridTemplateColumns: "1fr 200px 200px 200px",
      gap: "12px",
      height: "80px",
      alignItems: "center",
      backgroundColor: "#ffffff",
      justifyContent: "center",
      width: "100%",
      maxWidth: "1000px",
    },
    priceRow: {
      fontWeight: 600,
      fontSize: "16px",
      backgroundColor: "transparent",
      height: "80px",
    },
    evenRow: {
      backgroundColor: "transparent",
      height: "80px",
    },
    oddRow: {
      backgroundColor: "transparent",
      height: "80px",
    },
    featureLabelCell: {
      fontSize: "20px",
      color: "#333",
      fontWeight: 400,
      paddingLeft: "0px",
      lineHeight: "1.4",
      height: "80px",
      display: "flex",
      alignItems: "center",
      borderBottom: "1px solid #d0d0d0",
    },
    featureValueCellGray: {
      textAlign: "center",
      fontSize: "16px",
      color: "#333",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      height: "80px",
      backgroundColor: "#e8e8e8",
      borderBottom: "1px solid #d0d0d0",
    },
    featureValueCellWhite: {
      textAlign: "center",
      fontSize: "16px",
      color: "#333",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      height: "80px",
      backgroundColor: "#ffffff",
      borderBottom: "1px solid #d0d0d0",
    },
    featureValueCellGrayed: {
      textAlign: "center",
      fontSize: "16px",
      color: "#999",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      height: "80px",
      backgroundColor: "#f5f5f5",
      borderBottom: "1px solid #d0d0d0",
      opacity: 0.6,
    },
    checkIcon: {
      width: "20px",
      height: "20px",
    },
    checkIconGrayed: {
      width: "20px",
      height: "20px",
      opacity: 0.4,
    },
    dashIcon: {
      color: "#ccc",
      fontSize: "20px",
    },
    dashIconGrayed: {
      color: "#ddd",
      fontSize: "20px",
      opacity: 0.4,
    },
    tableActionButtonLarge: {
      marginTop: "30px",
      padding: "16px 32px",
      fontSize: "18px",
      fontWeight: 500,
      textTransform: "none",
      borderRadius: "8px",
      minWidth: "200px",
    },
    mobileContainer: {
      display: "flex",
      flexDirection: "column",
      minHeight: "100vh",
      padding: "20px",
      paddingBottom: "100px",
    },
    mobilePlanTabs: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: "30px",
      gap: "8px",
    },
    mobilePlanTab: {
      flex: 1,
      padding: "12px 8px",
      backgroundColor: "#e0e0e0",
      border: "none",
      borderRadius: "8px",
      fontSize: "16px",
      fontWeight: 500,
      color: "#333",
      cursor: "pointer",
      position: "relative",
      transition: "all 0.2s ease",
    },
    mobilePlanTabSelected: {
      backgroundColor: "#A70201",
      color: "white",
    },

    mobilePlanTabCurrent: {
      backgroundColor: "#4CAF50",
      color: "white",
      border: "2px solid #2E7D32",
    },

    mobilePlanTabContent: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      gap: "4px",
      position: "relative",
    },

    mobileCurrentPlanLabel: {
      fontSize: "10px",
      fontWeight: 600,
      textTransform: "uppercase",
      letterSpacing: "0.5px",
      opacity: 0.9,
    },

    mobileCurrentBadge: {
      position: "absolute",
      top: "-8px",
      right: "-8px",
      backgroundColor: "#4CAF50",
      color: "white",
      borderRadius: "50%",
      width: "16px",
      height: "16px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "10px",
      fontWeight: "bold",
      border: "1px solid #ffffff",
    },
    tabArrow: {
      position: "absolute",
      bottom: "-8px",
      left: "50%",
      transform: "translateX(-50%)",
      width: 0,
      height: 0,
      borderLeft: "8px solid transparent",
      borderRight: "8px solid transparent",
      borderTop: "8px solid #A70201",
    },
    mobileContent: {
      flex: 1,
      display: "flex",
      flexDirection: "column",
      gap: "20px",
    },
    mobilePriceSection: {
      backgroundColor: "transparent",
      padding: "20px",
      borderRadius: "8px",
      textAlign: "center",
    },
    mobilePriceLabel: {
      fontSize: "18px",
      fontWeight: 500,
      color: "#333",
      margin: "0 0 10px 0",
    },
    mobilePriceValue: {
      fontSize: "24px",
      fontWeight: 600,
      color: "black",
    },
    mobileFeaturesList: {
      borderRadius: "8px",
      overflow: "hidden",
    },
    mobileFeatureItem: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      textAlign: "center",
      padding: "16px 20px",
      borderBottom: "1px solid #e0e0e0",
      "&:last-child": {
        borderBottom: "none",
      },
    },
    mobileFeatureText: {
      fontSize: "14px",
      color: "#333",
      lineHeight: "1.4",
      marginBottom: "8px",
      textAlign: "center",
    },
    mobileFeatureCheckmark: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
    },
    featureLimitation: {
      fontSize: "12px",
      color: "#666",
      fontStyle: "italic",
    },
    fixedBottomButton: {
      position: "fixed",
      bottom: "20px",
      left: "50%",
      transform: "translateX(-50%)",
      backgroundColor: "#A70201",
      color: "white",
      padding: "16px 32px",
      borderRadius: "8px",
      fontSize: "16px",
      fontWeight: 500,
      textTransform: "none",
      border: "none",
      cursor: "pointer",
      zIndex: 9999,
      boxShadow: "0px 4px 12px rgba(0, 0, 0, 0.3)",
      minWidth: "200px",
      "&:disabled": {
        backgroundColor: "#ccc",
        color: "#666",
        cursor: "not-allowed",
      },
    },
  })
);
