export const TAGS = {
  "abstract-expressionism": "Abstrakt expressionism",
  "abstract": "Abstrakt konst",
  "acrylic": "Akryl",
  "aquarelle": "Akvarell",
  "architecture": "Arkitektur",
  "mixed-media": "Blandteknik",
  "flowers": "Blomster",
  "pencil": "Blyerts",
  "digital": "Digital",
  "animal": "Djur",
  "documentary-photography": "Dokumentärfotografi",
  "expressionism": "Expressionism",
  "fantasy": "Fantasi",
  "fashion": "Fashion",
  "figurative": "Figurativt",
  "photography": "Fotografi",
  "photorealism": "Fotorealism",
  "gallery": "Galleri",
  "street-art": "Gatukonst",
  "geometric": "Geometriskt",
  "glass": "Glas",
  "gouache": "Gouache",
  "graffiti": "Graffiti",
  "graphic": "Grafik",
  "group-exhibition": "Grupputställning",
  "seascape": "Havslandskap",
  "dogs": "Hundar",
  "illustration": "Illustration",
  "impressionism": "Impressionism",
  "installation": "Installation",
  "cats": "Katter",
  "ceramic": "Keramik",
  "charcoal": "Kol",
  "collage": "Kollage",
  "conceptual": "Konceptuell",
  "arts-craft": "Konsthantverk",
  "art-exhibition": "Konstutställning",
  "cubism": "Kubism",
  "celebrity": "Kändis",
  "landscape": "Landskap",

  "clay": "Lera",
  "food-drink": "Mat & dryck",
  "minimalism": "Minimalism",
  "pattern": "Mönster",
  "nature": "Natur",
  "nude": "Naket",
  "NFT": "NFT",
  
  "oil": "Olja",
  "pastel": "Pastell",
  "performance-art": "Performancekonst",
  "places": "Platser",
  "politics": "Politik",
  "pop-art": "Popkonst",
  "pop-culture": "Populärkultur",
  "portraiture": "Porträtt",
  "posters": "Posters",
  "print": "Prints",
  "realism": "Realism",
  "travel": "Resor",
  "surrealism": "Surrealism",
  "seasons": "Säsonger",
  "sculpture": "Skulptur",
  "still-life": "Stilleben",
  "big-city": "Storstad",
   
  "jewelry": "Smycken",
  "drawing": "Teckning",
  "textile": "Textil",
  "triptych": "Triptyk",
  "ink": "Tusch",
  "water": "Vatten",
 
  "video-art": "Videokonst",
  "mural": "Väggmålning",



};
