export const TECHNIQUES = {
    "oil": "Oil",
    "acrylic": "Acrylic",
    "aquarelle": "Aquarelle",
    "mixed-media": "Mixed media",
    "ceramic": "Ceramic",
    "pencil": "Pencil",
    "charcoal": "Charcoal",
    "clay": "Clay",
    "glass": "Glass",
    "textile": "Textile",
    "gouache": "Gouache",
    "ink": "Ink",
    "pastel": "Pastel",
    "collage": "Collage",
    "drawing": "Drawing",
    "photography": "Photography",
    "sculpture": "Sculpture",
    "digital": "Digital",
    "illustration": "Illustration",
    "video-art": "Video art",
    "performance-art": "Performance art",
    "triptych": "Triptych",
    "installation": "Installation",
    "mural": "Mural",
    "print": "Prints",
    "graphic": "Graphics"
  };

  export const THEMES = {
    "impressionism": "Impressionism",
    "abstract": "Abstract",
    "realism": "Realism",
    "surrealism": "Surrealism",
    "expressionism": "Expressionism",
    "cubism": "Cubism",
    "pop-art": "Pop art",
    "documentary-photography": "Documentary photography",
    "photorealism": "Photorealism",
    "abstract-expressionism": "Abstract expressionism",
    "graffiti": "Graffiti",
    "portraiture": "Portraiture",
    "arts-craft": "Arts & craft",
    "conceptual": "Conceptual",
    "street-art": "Street art",
    "still-life": "Still life",
    "landscape": "Landscape",
    "animal": "Animal",
    "architecture": "Architecture",
    "nature": "Nature",
    "fashion": "Fashion",
    "geometric": "Geometric",
    "flowers": "Flowers",
    "fantasy": "Fantasy",
    "pattern": "Pattern",
    "celebrity": "Celebrity",
    "pop-culture": "Pop culture",
    "minimalism": "Minimalism",
    "figurative": "Figurative",
    "places": "Places",
    "politics": "Politics",
    "water": "Water",
    "big-city": "Big city",
    "seasons": "Seasons",
    "cats": "Cats",
    "dogs": "Dogs",
    "nude": "Nude",
    "travel": "Travel",
    "food-drink": "Food & drink",
    "seascape": "Seascape",
    "art-exhibition": "Art exhibition",
    "gallery": "Gallery",
    "group-exhibition": "Group exhibition",
    "posters": "Posters",
    "artwork": "Artwork",
    "NFT": "NFT",
    "jewelry": "Jewelry",
  };